server:
  port: 8081

spring:
  application:
    name: springboot-keycloak
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/app-login
          jwk-set-uri: http://localhost:8080/auth/realms/app-login/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: app-login
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG